#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>
#include <QLabel>
#include "paintwidget.h"
#include "ising_model.h"

#define DEBUG

//generated by Qt Designer from mainwindow.ui form (see build-drawing-Desktop_Qt_5_3_MinGW_32bit-Debug/ui_mainwindow.h)
namespace Ui {
    class mainWindow;
}

class mainWindow : public qMainWindow {
    Q_OBJECT

public:
    explicit mainWindow(int l_size = 64, QWidget *parent = 0);

    ~mainWindow();

    int alg; //simulation algorithm: 1 for heat_bath, -1 for clasters
    bool Thread_status; //true when thread is working, false when terminated
    parameters p; //parameters of the model
    int l_size; //squareLattice size - number of rows or columns
    lattice *l; //lattice type of squareLattice, used in simulation

public
    slots:
            void Change_algo_label();

    void paint_resized(QSize old_size, QSize new_size);

    void recieveStep(int number);

    signals:
            void SendDeleteThread();

private
    slots:

private:
    Ui::mainWindow *ui;
    paintWidget *paintWidget; //new dynamically created widget
    QLabel *lb1;
    QLabel *lb2;
    QLabel *lb3;

    void draw_picture();
};

#endif // MAINWINDOW_H
